title: Systems Cyber
author: SystemsCyber
email: Jeremy.Daily@colostate.edu
description: > # this means to ignore newlines until "baseurl:"
  Resources and content related to the work and interests of 
  
  Dr. Jeremy Daily, Associate Professor of Systems Engineering at Colorado State University
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  SystemsCyber # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-cayman
